stages:
  - Preparación
  - Ejecución
  - Remoto

Instalar_dependencias:
  stage: Preparación
  allow_failure: false
  script:
    - echo "Preparando ... "

Ejecutar_programa:
  stage: Ejecución
  allow_failure: false
  script:
    - echo "Ejecutando ... "

deploy-desa:
  stage: Remoto
  before_script:
    - echo "Antes de script desarrollo"
  script:
    - echo "Inicio de actualizacion desarrollo bookrush"
    - sh /www/wwwroot/repositorios/actualizar_bookrush.sh
    - echo "Ejecucion en remoto Finalizada book rush..."
    - ls -la
  rules:
    - if: '$CI_COMMIT_TAG != "" && $CI_COMMIT_BRANCH=="diego"'  
  tags:
    - svritesur
deploy-prod:
  #image: alpine-latest
  stage: Remoto
  before_script:
    - echo "Antes de script produccion"
  script:
    - echo "Inicio de actualizacion produccion bookrush"
    - sh /www/wwwroot/repositorios/actualizar_bookrush_produccion.sh
    - echo "Ejecucion en remoto Finalizada book rush..."
  rules:
    - if: '$CI_COMMIT_TAG != "" && $CI_COMMIT_BRANCH=="produccion"'  
  tags:
    - svritesur
